CREATE USER user_write WITH PASSWORD 'writerpass';
GRANT CONNECT ON DATABASE hltv TO user_write;
GRANT USAGE ON SCHEMA public TO user_write;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO user_write;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO user_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT INSERT, UPDATE ON TABLES TO user_write;

CREATE USER user_read_only WITH PASSWORD 'readerpass';
GRANT CONNECT ON DATABASE hltv TO user_read_only;
GRANT USAGE ON SCHEMA public TO user_read_only;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO user_read_only;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO user_read_only;